TOPDIR ?= ../..
include $(TOPDIR)/.config

$(RSCP_SUPPORT)_SRC += protocols/rscp/rscp.c protocols/rscp/rscp_net.c \
 protocols/rscp/rscp_io.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
