TOPDIR ?= ../..
include $(TOPDIR)/.config

$(RSCP_SUPPORT)_SRC += protocols/rscp/rscp.c protocols/rscp/rscp_net.c \
 protocols/rscp/rscp_io.c protocols/rscp/crc32.c protocols/rscp/mtime.c protocols/rscp/timer.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
