TOPDIR ?= ../..
include $(TOPDIR)/.config

$(VSCP_SUPPORT)_SRC += protocols/vscp/vscp.c protocols/vscp/vscp_net.c

# $(VSCP_SUPPORT)_ECMD_SRC += \
# 	protocols/vscp/ecmd.c
##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
